name: GitHub Actions Shell Script Test

on: [push]

jobs:
  test-execution:
    name: Use Linux commands
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Permission Setting
        # 新しいファイル名に変更し、実行権限を与えます
        run: chmod +x saidai.sh test-saidai.sh
      - name: Test Run
        # 新しいテストスクリプトを実行します
        run: ./test-saidai.sh
